---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

SSViewer:
  theme: 'simple'
Blog:
  extensions:
    - WidgetPageExtension
BlogPost:
  extensions:
    - WidgetPageExtension
Calendar:
    timezone: America/Chicago
    language: EN
BlogMigrationTask:
    run_during_dev_build: false
CalendarEvent:
  show_in_sitetree: false
  echo_progress: true
SiteConfig:
  extensions:
    - SiteConfigExtension
Page:
  extensions:
    - OpenGraphExtension
FormSpamProtectionExtension:
    default_spam_protector: NocaptchaProtector