---
Name: uima
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  rewrite_hash_links: false
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
  default_spam_protector: NocaptchaProtector
SiteTree:
  extensions:
    - SilverStripe\ORM\Search\FulltextSearchable
SilverStripe\ORM\Search\FulltextSearchable:
  enabled: ‘true’
Calendar:
  extensions:
    - SilverStripe\Lumberjack\Model\Lumberjack
CalendarEvent:
  show_in_sitetree: false
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    'file':
      'public': '0644'
      'private': '0600'