---
Name: uima
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: mysite
SilverStripe\View\SSViewer:
  rewrite_hash_links: false
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
SilverStripe\SpamProtection\Extension\FormSpamProtectionExtension:
  default_spam_protector: NocaptchaProtector
SiteTree:
  extensions:
    - SilverStripe\ORM\Search\FulltextSearchable
SilverStripe\ORM\Search\FulltextSearchable:
  enabled: ‘true’