---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
Blog:
  extensions:
    - WidgetPageExtension
BlogPost:
  extensions:
    - WidgetPageExtension
Calendar:
    timezone: America/Chicago
    language: EN
BlogMigrationTask:
    run_during_dev_build: false
CalendarEvent:
  show_in_sitetree: false
FilesystemPublisher:
    static_base_url: http://localhost:8888/uima
    echo_progress: true
---
Name: mysiteconfig_redirector
After: 'staticpublishqueue/*'
---
RedirectorPage:
  extensions:
    - PublishableRedirectorPage
DailyArtBlogPost:
  extensions:
    - PublishableDailyArtBlogPost
---
Name: mysiteconfig_staticpublishqueue
After: 'staticpublishqueue/*','#mysiteconfig_redirector'
---
SiteTree:
  extensions:
    - PublishableSiteTree
    - SiteTreePublishingEngine
    - FilesystemPublisher('cache', 'html')
---
Only:
  environment: live
---
Director:
  alternate_protocol: 'https'