---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
BlogEntry:
  extensions:
    - WidgetPageExtension
BlogHolder:
  extensions:
    - WidgetPageExtension
Calendar:
    timezone: America/Chicago
    language: EN